begin;
insert into public.app_members(email)values('worker.member@example.com');
insert into public.companies(id,name,last_activity_at)values('cccccccc-cccc-cccc-cccc-cccccccccccc','Sync Co','2026-01-01');
insert into public.google_mailbox_connections(email,refresh_token_encrypted,refresh_token_iv,refresh_token_tag)values('worker.member@example.com','encrypted','iv','tag');
create function pg_temp.expect(ok boolean,label text)returns void language plpgsql as $$begin if not coalesce(ok,false)then raise exception 'SYNC TEST: %',label;end if;end$$;
create function pg_temp.refused(q text)returns boolean language plpgsql as $$begin execute q;return false;exception when others then return true;end$$;
create temp table job(id uuid,lease uuid);grant all on job to authenticated,vanquish_worker;
set local role authenticated;
select set_config('request.jwt.claims','{"role":"authenticated","email":"worker.member@example.com"}',true);
select public.configure_crm_sync(true,false);
select public.request_crm_sync();select public.request_crm_sync();
select pg_temp.expect((select count(*)from public.crm_sync_jobs)=2,'queue idempotent');
select pg_temp.expect(pg_temp.refused('select public.worker_claim_sync()'),'member cannot claim machine lease');
reset role;set local role vanquish_worker;
insert into job select id,lease from public.worker_claim_sync();
select pg_temp.expect(pg_temp.refused('select * from public.google_mailbox_connections'),'worker has no direct credential table access');
select pg_temp.expect(pg_temp.refused(format('select public.worker_sync_context(%L,%L)',(select id from job),gen_random_uuid())),'unowned lease denied');
select public.worker_commit_sync((select id from job),(select lease from job),jsonb_build_array(jsonb_build_object('id','provider-1','companyId','cccccccc-cccc-cccc-cccc-cccccccccccc','occurredAt','2026-09-01T12:00:00Z','subject','Private subject','status','matched')),'{"historyId":"10"}',true);
reset role;
select pg_temp.expect((select count(*)from public.interactions where source_event_id is not null)=1,'matched source published once');
select pg_temp.expect((select subject from public.interactions where source_event_id is not null) in ('Email activity','Calendar activity'),'subjects excluded without consent');
select pg_temp.expect((select last_activity_at from public.companies where id='cccccccc-cccc-cccc-cccc-cccccccccccc')='2026-09-01T12:00:00Z','activity updated');
-- Replay same source then cancellation in a fresh lease.
update public.crm_sync_jobs set status='pending',completed_at=null where id=(select id from job);
update public.crm_sync_jobs set next_run_at=now()+interval '1 hour' where id<>(select id from job);
truncate job;set local role vanquish_worker;
insert into job select id,lease from public.worker_claim_sync();
select public.worker_commit_sync((select id from job),(select lease from job),jsonb_build_array(jsonb_build_object('id','provider-1','status','deleted')),'{"historyId":"11"}',true);
reset role;
select pg_temp.expect((select count(*)from public.interactions where source_event_id is not null)=1,'cancellation keeps one historical record');
select pg_temp.expect((select count(*)from public.interactions where source_event_id is not null and archived_at is null)=0,'cancelled interaction archived');
select pg_temp.expect((select last_activity_at from public.companies where id='cccccccc-cccc-cccc-cccc-cccccccccccc')='2026-01-01','cancellation restores tracker baseline');
set local role authenticated;select set_config('request.jwt.claims','{"role":"authenticated","email":"worker.member@example.com"}',true);
select public.configure_crm_sync(false,false);
select pg_temp.expect((select count(*)from public.crm_sync_jobs where status='pending')=0,'opt out stops queued jobs');
reset role;set local role vanquish_worker;
select pg_temp.expect(pg_temp.refused(format('select public.worker_commit_sync(%L,%L,''[]'',''{}'',true)',(select id from job),(select lease from job))),'opt out invalidates an existing lease');
reset role;rollback;
