begin;
insert into public.app_members(email,display_name) values ('flow.a@example.com','A'),('flow.b@example.com','B'),('flow.c@example.com','C');
insert into public.member_permissions(email,permission) values ('flow.a@example.com','admin'),('flow.a@example.com','documents'),('flow.a@example.com','portfolio');
insert into public.companies(id,name) values ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','Original');
create function pg_temp.expect(ok boolean,label text) returns void language plpgsql as $$begin if not coalesce(ok,false) then raise exception 'WORKFLOW TEST: %',label; end if;end$$;
create function pg_temp.refused(q text) returns boolean language plpgsql as $$begin execute q; return false;exception when others then return true;end$$;
create temp table ids(k text primary key,v uuid); grant all on ids to authenticated;
set local role authenticated;
select set_config('request.jwt.claims','{"role":"authenticated","email":"flow.a@example.com"}',true);
insert into ids values ('proposal',public.propose_change('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',null,'name','Accepted','Evidence'));
select pg_temp.expect(public.decide_change((select v from ids where k='proposal'),true)='accepted','accept proposal');
select pg_temp.expect((select name from public.companies where id='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb')='Accepted','value updated');
select pg_temp.expect(public.decide_change((select v from ids where k='proposal'),true)='accepted','decision idempotent');
insert into ids values ('conflict',public.propose_change('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',null,'name','Stale','Evidence'));
update public.companies set name='Newer' where id='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
select pg_temp.expect(public.decide_change((select v from ids where k='conflict'),true)='conflict','stale value conflicts');
select pg_temp.expect((select name from public.companies where id='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb')='Newer','newer value preserved');
select pg_temp.expect(pg_temp.refused($q$select public.propose_change('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',null,'deleted_at','x','Invalid')$q$),'field allowlist');
insert into ids values ('private',public.comment_post_visible('home',null,null,null,'page','Home','Snapshot','Private message',array['flow.b@example.com'],array['flow.b@example.com']));
select pg_temp.expect((select visible_to is not null and value_snapshot='Snapshot' from public.record_comments where id=(select v from ids where k='private')),'snapshot and visibility');
select set_config('request.jwt.claims','{"role":"authenticated","email":"flow.c@example.com"}',true);
select pg_temp.expect((select count(*) from public.record_comments where id=(select v from ids where k='private'))=0,'unselected reader excluded');
select pg_temp.expect(pg_temp.refused(format('select public.comment_set_resolved(%L,true)',(select v from ids where k='private'))),'resolve cannot bypass private thread');
select pg_temp.expect(pg_temp.refused(format('select public.comment_post_context(''home'',null,null,%L,''page'',''Home'',null,''Intrusion'')',(select v from ids where k='private'))),'reply cannot bypass private thread');
select pg_temp.expect((select count(*) from public.audit_log)=0,'audit admin only');
select set_config('request.jwt.claims','{"role":"authenticated","email":"flow.b@example.com"}',true);
select pg_temp.expect((select count(*) from public.record_comments where id=(select v from ids where k='private'))=1,'recipient sees private thread');
insert into ids values ('reply',public.comment_post_context('home',null,null,(select v from ids where k='private'),'page','Home',null,'Private reply'));
select pg_temp.expect((select visible_to is not null from public.record_comments where id=(select v from ids where k='reply')),'reply inherits privacy');
select pg_temp.expect(pg_temp.refused(format('select public.comment_edit(%L,''Leak'',array[''flow.c@example.com''])',(select v from ids where k='reply'))),'mentions cannot invite outside thread');
select set_config('request.jwt.claims','{"role":"authenticated","email":"flow.a@example.com"}',true);
select pg_temp.expect((select count(*) from public.audit_log where entity_table='companies' and operation='UPDATE')=2,'writes audited separately');
select pg_temp.expect(pg_temp.refused('delete from public.audit_log'),'audit immutable');
reset role;
rollback;
