begin;
insert into public.app_members(email) values('source.admin@example.com'),('source.reader@example.com'),('source.other@example.com');
insert into public.member_permissions(email,permission) values('source.admin@example.com','admin'),('source.admin@example.com','documents'),('source.admin@example.com','portfolio'),('source.reader@example.com','documents');
insert into public.companies(id,name) values('eeeeeeee-0000-0000-0000-000000000001','Source Company'),('eeeeeeee-0000-0000-0000-000000000002','Merge Company');
insert into public.deals(id,company_id,name,restricted,stage_id) values('eeeeeeee-0000-0000-0000-000000000003','eeeeeeee-0000-0000-0000-000000000001','Private round',true,(select id from public.pipeline_stages order by sort_order limit 1));
insert into public.deal_access_members(deal_id,member_email,access_role) values('eeeeeeee-0000-0000-0000-000000000003','source.reader@example.com','viewer');
insert into public.deal_assignees(deal_id,member_email,assigned_by) values('eeeeeeee-0000-0000-0000-000000000003','source.reader@example.com','source.admin@example.com');
insert into public.documents(id,company_id,deal_id,name,source,drive_file_id,entity_role) values('eeeeeeee-0000-0000-0000-000000000004','eeeeeeee-0000-0000-0000-000000000001','eeeeeeee-0000-0000-0000-000000000003','Evidence.pdf','drive_link','evidence','TARGET');
update public.documents set storage_path='source/private.pdf' where id='eeeeeeee-0000-0000-0000-000000000004';
insert into storage.objects(bucket_id,name) values('documents','source/private.pdf');
create function pg_temp.expect(ok boolean,label text)returns void language plpgsql as $$begin if not coalesce(ok,false)then raise exception 'SOURCE TEST: %',label;end if;end$$;
create function pg_temp.refused(q text)returns boolean language plpgsql as $$begin execute q;return false;exception when insufficient_privilege then return true;end$$;
create temp table ids(k text primary key,v uuid);grant all on ids to authenticated;
set local role authenticated;
select set_config('request.jwt.claims','{"role":"authenticated","email":"source.admin@example.com"}',true);
insert into ids values('document',public.comment_post_visible('documents',null,null,null,'document:eeeeeeee-0000-0000-0000-000000000004','Evidence',null,'Document note'));
insert into ids values('chat_allowed',public.chat_start_direct('source.reader@example.com'));
insert into ids values('chat_denied',public.chat_start_direct('source.other@example.com'));
select public.share_comment_to_chat((select v from ids where k='document'),(select v from ids where k='chat_allowed'));
select pg_temp.expect(pg_temp.refused(format('select public.share_comment_to_chat(%L,%L)',(select v from ids where k='document'),(select v from ids where k='chat_denied'))),'chat sharing rejects inaccessible recipients');
select pg_temp.expect((select count(*) from public.chat_messages where body like 'Workspace comment:%')=1,'chat receives source link only');
insert into ids values('deal',public.comment_post_visible('pipeline',null,null,null,'deal:eeeeeeee-0000-0000-0000-000000000003','Private round',null,'Pipeline note'));
insert into ids values('proposal',public.propose_change('eeeeeeee-0000-0000-0000-000000000001','eeeeeeee-0000-0000-0000-000000000003','notes','Proposal','Evidence'));
select set_config('request.jwt.claims','{"role":"authenticated","email":"source.reader@example.com"}',true);
select pg_temp.expect((select count(*) from public.record_comments where id=(select v from ids where k='document'))=1,'document reader can read source discussion');
select pg_temp.expect(pg_temp.refused($q$select public.set_deal_assignee('eeeeeeee-0000-0000-0000-000000000003','source.reader@example.com',false)$q$),'reader cannot delete assignment via definer');
select pg_temp.expect(pg_temp.refused(format('select public.decide_change(%L,true)',(select v from ids where k='proposal'))),'reader cannot apply proposal via definer');
select set_config('request.jwt.claims','{"role":"authenticated","email":"source.other@example.com"}',true);
select pg_temp.expect((select count(*) from storage.objects where bucket_id='documents' and name='source/private.pdf')=0,'hidden document binary is not downloadable');
select pg_temp.expect((select count(*) from public.record_comments where id in(select v from ids))=0,'source comments honor deal and file permissions');
select pg_temp.expect(pg_temp.refused($q$select public.comment_post_context('documents',null,null,null,'document:eeeeeeee-0000-0000-0000-000000000004','Guess',null,'Intrusion')$q$),'source mutation cannot bypass file permission');
select pg_temp.expect(pg_temp.refused($q$select public.comment_post_context('pipeline',null,null,null,'deal:eeeeeeee-0000-0000-0000-000000000003','Guess',null,'Intrusion')$q$),'pipeline anchor cannot bypass deal permission');
select set_config('request.jwt.claims','{"role":"authenticated","email":"source.admin@example.com"}',true);
select pg_temp.expect(pg_temp.refused($q$select public.comment_post_context('documents',null,null,null,'document:eeeeeeee-0000-0000-0000-000000000004','Evidence',null,'Mention',array['source.other@example.com'])$q$),'mention cannot grant source access');
select public.merge_companies('eeeeeeee-0000-0000-0000-000000000001','eeeeeeee-0000-0000-0000-000000000002');
select pg_temp.expect((select merged_into_id from public.companies where id='eeeeeeee-0000-0000-0000-000000000002')='eeeeeeee-0000-0000-0000-000000000001','merge archives original identity with destination');
select public.configure_deal_access('eeeeeeee-0000-0000-0000-000000000003',true,'[]');
select set_config('request.jwt.claims','{"role":"authenticated","email":"source.reader@example.com"}',true);
select pg_temp.expect((select count(*) from public.record_comments where id=(select v from ids where k='document'))=0,'revoking deal access hides document discussion');
select pg_temp.expect((select count(*) from storage.objects where bucket_id='documents' and name='source/private.pdf')=0,'revoked document access also hides the binary');
with removed as (delete from storage.objects where bucket_id='documents' and name='source/private.pdf' returning id) select pg_temp.expect((select count(*) from removed)=0,'revoked reader cannot delete the binary');
reset role;
rollback;
