import { formatMonthYear } from "../dates";

// How a deal is identified in lists and cards. A deal is one opportunity or
// evaluation of a company; `round` is optional and only shown when known.
// Nothing is inferred: a missing round is simply left out.

export type DealDisplayInput = {
  name: string;
  round?: string | null;
  companyName?: string | null;
  firstSeenAt?: string | null;
  createdAt?: string | null;
};

// Names generated by imports or the old New Deal default carry no meaning of
// their own ("Acme — tracker import", "Acme — new deal").
const TECHNICAL_SUFFIX = /\s*[—–-]\s*(tracker import|new deal)\s*$/i;

function normalize(value: string | null | undefined) {
  return (value ?? "").trim().toLocaleLowerCase();
}

// The part of the deal name that tells it apart from its company, or null
// when the name only repeats the company plus a technical suffix.
export function distinctDealName(input: DealDisplayInput) {
  const stripped = input.name.replace(TECHNICAL_SUFFIX, "").trim();
  if (!stripped) return null;
  if (input.companyName && normalize(stripped) === normalize(input.companyName)) {
    return null;
  }
  return stripped;
}

export function dealLabel(input: DealDisplayInput) {
  const name = distinctDealName(input);
  const round = input.round?.trim() || null;
  const parts: string[] = [];

  if (name) parts.push(name);
  if (round && !normalize(name).includes(normalize(round))) parts.push(round);
  if (parts.length > 0) return parts.join(" · ");

  if (input.firstSeenAt) return `First seen ${formatMonthYear(input.firstSeenAt)}`;
  if (input.createdAt) return `Added ${formatMonthYear(input.createdAt)}`;
  return "Deal";
}

// Heading for a deal page: the distinct name when there is one, otherwise the
// company name so the page is never titled with an import artifact.
export function dealTitle(input: DealDisplayInput) {
  return distinctDealName(input) ?? input.companyName ?? input.name;
}
