"use client";
import {useRef,useState,useTransition} from "react";
import Link from "next/link";
import SelectMenu from "@/components/SelectMenu";
import {importMailAttachment,loadDocumentTargets} from "@/lib/documents/intake-actions";
import type {MailAttachment} from "@/lib/google/mail-types";
export default function AttachmentImport({messageId,file}:{messageId:string;file:MailAttachment}) {
  const dialog=useRef<HTMLDialogElement>(null);const [targets,setTargets]=useState<{companyId:string;dealId:string|null;label:string}[]>([]);
  const [target,setTarget]=useState("0"),[message,setMessage]=useState(""),[saved,setSaved]=useState(false),[busy,start]=useTransition();
  if(!file.id)return null;
  return <><button className="rounded-full border border-neutral-200 px-3 py-1.5 text-[11px] font-semibold text-cyan-800 hover:border-cyan-400" disabled={busy} onClick={()=>start(async()=>{const choices=await loadDocumentTargets();if(!choices){setMessage("Documents access is required.");dialog.current?.showModal();return;}setTargets(choices);setMessage("");setSaved(false);dialog.current?.showModal();})}>Import to CRM</button>
  <dialog ref={dialog} className="vq-card-static fixed inset-0 m-auto w-[min(440px,calc(100%-24px))] rounded-2xl bg-white p-5 backdrop:bg-black/20"><div className="flex items-center justify-between gap-3"><h2 className="text-[15px] font-semibold text-ink">Import attachment</h2><button type="button" aria-label="Close attachment import" onClick={()=>dialog.current?.close()} className="rounded-full border border-neutral-200 px-3 py-1 text-[12px]">Close</button></div><p className="my-3 break-words text-[13px] text-neutral-500">{file.name}</p>{!saved&&targets.length>0&&<><label className="text-[12px] text-neutral-600">Company or round<SelectMenu value={target} onChange={setTarget} options={targets.map((t,i)=>({value:String(i),label:t.label}))}/></label><p className="mt-3 text-[11px] text-neutral-400">This copies the attachment to the internal document workspace and extracts text locally for review.</p><button disabled={busy} className="mt-4 rounded-full bg-ink px-4 py-2 text-[12px] font-semibold text-white disabled:opacity-40" onClick={()=>start(async()=>{const chosen=targets[Number(target)];const result=await importMailAttachment({...chosen,messageId,attachmentId:file.id!,name:file.name,mime:file.mimeType});setMessage(result.ok?"Attachment saved. Review its document metadata before applying it.":result.message);setSaved(result.ok);})}>Import attachment</button></>}{message&&<p role="status" className="mt-3 text-[12px] text-cyan-800">{message}</p>}{saved&&<Link href="/documents" className="mt-3 inline-block text-[12px] font-semibold text-cyan-800" onClick={()=>dialog.current?.close()}>Open document review →</Link>}</dialog></>;
}
