"use client";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import SelectMenu from "@/components/SelectMenu";
import { importDriveFile,listDriveFolder,reviewDocument,organizeDriveDocument,reprocessDocument,monitorDriveFolder } from "@/lib/documents/intake-actions";
export type IntakeDocument={id:string;name:string;company_id:string|null;deal_id:string|null;drive_file_id:string|null;created_at:string;analysis:{expected_revision:number;extraction_status:string;extracted_text:string;suggested_type_id:string|null;suggested_date:string|null;confidence:string;status:string}|null;versions:{revision:number;created_at:string}[]};
type DriveFile={id:string;name:string;mimeType:string};
export default function DocumentIntake({documents,types,targets,available,sources,jobs,errors}:{documents:IntakeDocument[];types:{id:string;name:string}[];targets:{companyId:string;dealId:string|null;label:string}[];available:boolean;sources:{id:string;folder_id:string;company_id:string;deal_id:string|null;enabled:boolean}[];jobs:{id:string;service:string;status:string;drive_source_id:string|null;error_code:string|null}[];errors:{source_id:string;provider_id:string;code:string}[]}) {
  const router=useRouter();const [busy,start]=useTransition(),[message,setMessage]=useState("");
  const [folder,setFolder]=useState(""),[fileId,setFileId]=useState(""),[files,setFiles]=useState<DriveFile[]>([]),[nextPage,setNextPage]=useState<string|undefined>(),[targetIndex,setTargetIndex]=useState("0");
  const [selection,setSelection]=useState<Record<string,string>>({}),[dates,setDates]=useState<Record<string,string>>({}),[moveTo,setMoveTo]=useState<Record<string,string>>({});
  const button="rounded-full border border-neutral-200 px-3 py-2 text-[12px] font-semibold text-ink hover:border-cyan-400 disabled:opacity-40";
  const input="rounded-xl border border-neutral-200 px-3 py-2 text-[13px] outline-none focus:border-cyan-400 focus:ring-2 focus:ring-cyan-100";
  function importFile(id:string){const target=targets[Number(targetIndex)];if(!target)return;start(async()=>{const result=await importDriveFile(id,target);setMessage(result.ok?(result.data.analyzed?"File imported. Review its suggested metadata below.":"File imported; analysis could not be registered. Reprocess it below."):result.message);if(result.ok)router.refresh();});}
  async function loadFolder(more=false){const result=await listDriveFolder(folder,more?nextPage:undefined);if(result.ok){setFiles(current=>more?[...current,...result.data.files]:result.data.files);setNextPage(result.data.nextPageToken);}else setMessage(result.message);}
  return <div className="flex flex-col gap-5"><section className="vq-card rounded-[14px] bg-white p-5"><h2 className="text-[15px] font-semibold text-ink">Import from Drive</h2><p className="mt-1 text-[12px] text-neutral-500">Choose a company or round before importing. Text is extracted locally; suggested metadata stays in review until approved.</p><div className="mt-3 flex flex-wrap gap-3 text-[12px] font-semibold text-cyan-800"><a href="/api/connections/google/start?drive=read">Connect Drive for reading</a><a href="/api/connections/google/start?drive=write">Allow Drive rename and move</a></div><p className="mt-1 text-[11px] text-neutral-400">Drive management asks Google for permission to manage your files. Reading asks for read access only.</p>
  <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-[12px] text-neutral-600">Destination<SelectMenu value={targetIndex} onChange={setTargetIndex} options={targets.map((target,i)=>({value:String(i),label:target.label}))}/></label><label className="flex flex-col text-[12px] text-neutral-600">Drive file ID<input value={fileId} onChange={e=>setFileId(e.target.value)} className={input} placeholder="File ID from the Drive URL"/></label></div><button disabled={busy||!fileId||!targets.length} className={`${button} mt-3`} onClick={()=>importFile(fileId)}>Import selected file</button>
  <div className="mt-4 flex flex-wrap gap-2"><input aria-label="Drive folder ID" value={folder} onChange={e=>setFolder(e.target.value)} className={input} placeholder="Drive folder ID"/><button disabled={busy||!folder} className={button} onClick={()=>start(()=>loadFolder())}>Detect files in folder</button></div><button disabled={busy||!folder||!targets.length} className={`${button} mt-3`} onClick={()=>start(async()=>{const result=await monitorDriveFolder(folder,targets[Number(targetIndex)]);setMessage(result.message);router.refresh();})}>Monitor this folder automatically</button><p className="mt-1 text-[11px] text-neutral-400">Monitoring publishes future files in this folder to the selected company or round. Metadata proposals still require review.</p><div className="mt-3 divide-y divide-neutral-100">{files.map(file=><div key={file.id} className="flex items-center justify-between gap-3 py-2 text-[12px]"><span className="min-w-0 break-words">{file.name}</span><button disabled={busy||file.mimeType==="application/vnd.google-apps.folder"} className={button} onClick={()=>importFile(file.id)}>Import</button></div>)}</div>{nextPage&&<button disabled={busy} className={button} onClick={()=>start(()=>loadFolder(true))}>Load more files</button>}</section>
  <section className="vq-card-static rounded-[14px] bg-white p-5"><h2 className="text-[15px] font-semibold text-ink">Monitored folders</h2>{!sources.length&&<p className="mt-3 text-[12px] text-neutral-400">No monitored folders.</p>}{sources.map(source=><div key={source.id} className="mt-3 flex flex-wrap items-center justify-between gap-3 text-[12px]"><span className="break-all text-neutral-600">{source.folder_id} · {source.enabled?"Enabled":"Paused"} · {jobs.find(job=>job.drive_source_id===source.id)?.status??"No run yet"}</span><button disabled={busy} className={button} onClick={()=>start(async()=>{const result=await monitorDriveFolder(source.folder_id,{companyId:source.company_id,dealId:source.deal_id},!source.enabled);setMessage(result.message);router.refresh();})}>{source.enabled?"Pause":"Resume"}</button></div>)}{errors.map(error=><p key={`${error.source_id}:${error.provider_id}`} className="mt-3 text-[12px] text-amber-700">File {error.provider_id}: {error.code.replaceAll("_"," ")}. Check its existing CRM destination before importing it into this source.</p>)}</section>
  {!available&&<p className="text-[13px] text-neutral-500">Document review is awaiting the workspace schema update.</p>}
  {message&&<p role="status" className="text-[13px] text-cyan-800">{message}</p>}
  <div className="vq-card-grid grid gap-5 lg:grid-cols-2">{documents.map(doc=>{const analysis=doc.analysis;const type=selection[doc.id]??analysis?.suggested_type_id??"";const date=dates[doc.id]??analysis?.suggested_date??"";return <article key={doc.id} id={`document-${doc.id}`} data-comment-anchor={`document:${doc.id}`} data-comment-label={doc.name} data-comment-value={doc.name} className="vq-card rounded-[14px] bg-white p-5"><h2 className="break-words text-[14px] font-semibold text-ink">{doc.name}</h2>{doc.company_id&&<Link href={`/companies/${doc.company_id}${doc.deal_id?`/deals/${doc.deal_id}`:""}#documents`} className="mt-1 inline-block text-[12px] text-cyan-800">Open record →</Link>}<p className="mt-2 text-[11px] text-neutral-400">{analysis?.status??"Unprocessed"} · {analysis?.extraction_status??"No extraction"} · {doc.versions.length} metadata revisions</p>
    {analysis?.extracted_text&&<details className="mt-3 text-[12px]"><summary className="cursor-pointer font-semibold text-neutral-600">Extracted text (first 25 PDF pages)</summary><pre className="mt-2 max-h-52 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-neutral-50 p-3 font-sans text-neutral-500">{analysis.extracted_text}</pre></details>}
    {analysis?.status==="pending"&&<><label className="mt-3 block text-[12px] text-neutral-600">Document type<SelectMenu value={type} onChange={value=>setSelection(current=>({...current,[doc.id]:value}))} options={types.map(t=>({value:t.id,label:t.name}))} placeholder="Choose type"/></label><label className="mt-3 flex flex-col text-[12px] text-neutral-600">Document date<input type="date" className={input} value={date} onChange={e=>setDates(current=>({...current,[doc.id]:e.target.value}))}/></label><p className="mt-2 text-[11px] text-neutral-400">{analysis.confidence==="rule"?"Suggested by a local text rule. Confirm the type and effective date.":"Classification needs human review."} Approval applies the canonical filename to this CRM document.</p><div className="mt-3 flex gap-2">{[false,true].map(dismiss=><button key={String(dismiss)} disabled={busy||!dismiss&&!type} className={button} onClick={()=>start(async()=>{const result=await reviewDocument(doc.id,type,date||null,analysis.expected_revision,dismiss);setMessage(result.message);if(result.ok)router.refresh();})}>{dismiss?"Dismiss":"Apply metadata"}</button>)}</div></>}
    {(!analysis||analysis.status==="conflict")&&<button disabled={busy} className={`${button} mt-3`} onClick={()=>start(async()=>{const result=await reprocessDocument(doc.id);setMessage(result.ok?"Document processed. Check the proposed metadata.":result.message);router.refresh();})}>Reprocess document</button>}
    {doc.drive_file_id&&<div className="mt-4 border-t border-neutral-100 pt-3"><label className="flex flex-col text-[12px] text-neutral-600">Move to folder (optional)<input className={input} value={moveTo[doc.id]??""} onChange={e=>setMoveTo(current=>({...current,[doc.id]:e.target.value}))} placeholder="Drive folder ID"/></label><button className={`${button} mt-2`} disabled={busy} onClick={()=>{if(!window.confirm("Apply this CRM filename and optional folder move to the actual file in Google Drive?"))return;start(async()=>{const result=await organizeDriveDocument(doc.id,moveTo[doc.id]||undefined);setMessage(result.ok?"Drive file updated.":result.message);});}}>Apply name / move in Drive</button></div>}
    <details className="mt-3 text-[11px] text-neutral-500"><summary className="cursor-pointer">Version history</summary>{doc.versions.sort((a,b)=>b.revision-a.revision).map(version=><p key={version.revision} className="mt-1">Revision {version.revision} · {new Date(version.created_at).toLocaleString()}</p>)}</details>
  </article>})}</div></div>;
}
