"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {FormSelectMenu} from "@/components/SelectMenu";
import {savePortfolioSignal,saveWatchRule,resolvePortfolioSignal} from "@/lib/workflows/actions";
import {evaluateWatchRules,type WatchRule,type MetricObservation} from "@/lib/portfolio/monitoring";
export type PortfolioSignal={id:string;investment_id:string;title:string;source_url:string;observed_on:string;severity:string;status:string;notes:string|null};
export default function PortfolioScorecard({investments,observations,rules,signals,now}:{investments:{id:string;label:string}[];observations:MetricObservation[];rules:WatchRule[];signals:PortfolioSignal[];now:string}){
  const [busy,start]=useTransition(),[message,setMessage]=useState("");const router=useRouter();
  const input="rounded-xl border border-neutral-200 px-3 py-2 text-[12px] outline-none focus:border-cyan-400 focus:ring-2 focus:ring-cyan-100";
  const button="w-fit rounded-full bg-ink px-4 py-2 text-[12px] font-semibold text-white disabled:opacity-40";
  const scorecard=evaluateWatchRules(rules,observations,new Date(now));
  const label=(id:string)=>investments.find(i=>i.id===id)?.label??id;
  const select=<FormSelectMenu name="investmentId" defaultValue={investments[0]?.id} options={investments.map(i=>({value:i.id,label:i.label}))}/>;
  return <div className="flex flex-col gap-5"><section className="vq-card-static rounded-[14px] bg-white p-5"><h2 className="text-[15px] font-semibold text-ink">Monitoring scorecard</h2><p className="mt-1 text-[12px] text-neutral-500">Rules compare the latest dated value in the same unit. Missing or stale evidence is visible; future observations are excluded.</p><div className="mt-3 divide-y divide-neutral-100">{!scorecard.length&&<p className="py-4 text-[12px] text-neutral-400">Add watch rules to build the scorecard.</p>}{scorecard.map(item=><div key={item.rule.id} className="flex flex-wrap justify-between gap-3 py-3 text-[12px]"><div><strong className="text-ink">{label(item.rule.investment_id)} · {item.rule.metric}</strong><p className="text-neutral-400">Target {item.rule.minimum??"−∞"} to {item.rule.maximum??"∞"} {item.rule.unit} · max age {item.rule.stale_after_days} days</p></div><div className={item.status==="within range"?"text-cyan-800":"text-amber-700"}>{item.latest?`${Number(item.latest.value).toLocaleString()} ${item.rule.unit} · `:""}{item.status}</div></div>)}</div></section>
  <div className="vq-card-grid grid gap-5 lg:grid-cols-2"><section className="vq-card rounded-[14px] bg-white p-5"><h2 className="text-[15px] font-semibold text-ink">Watch rule</h2><form className="mt-3 grid gap-3" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);start(async()=>{const result=await saveWatchRule(form);setMessage(result.message);if(result.ok)router.refresh();});}}><label className="text-[12px] text-neutral-600">Investment{select}</label><input required name="metric" aria-label="Rule metric" placeholder="Metric (match the observation name)" className={input}/><input required name="unit" aria-label="Rule unit" placeholder="Unit (match the observation unit)" className={input}/><div className="grid grid-cols-2 gap-2"><input name="minimum" type="number" step="any" aria-label="Minimum" placeholder="Minimum" className={input}/><input name="maximum" type="number" step="any" aria-label="Maximum" placeholder="Maximum" className={input}/></div><label className="flex flex-col text-[12px] text-neutral-600">Maximum observation age (days)<input required name="staleDays" type="number" min={1} max={3660} defaultValue={90} className={input}/></label><button className={button} disabled={busy||!investments.length}>Save rule</button></form></section>
  <section className="vq-card rounded-[14px] bg-white p-5"><h2 className="text-[15px] font-semibold text-ink">External signal</h2><p className="mt-1 text-[12px] text-neutral-500">Record a verified external event and its source for post-investment follow-up.</p><form className="mt-3 grid gap-3" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);start(async()=>{const result=await savePortfolioSignal(form);setMessage(result.message);if(result.ok)router.refresh();});}}><label className="text-[12px] text-neutral-600">Investment{select}</label><input required name="title" maxLength={200} aria-label="Signal title" placeholder="Signal title" className={input}/><input required name="sourceUrl" type="url" aria-label="Signal source URL" placeholder="https://source…" className={input}/><input required name="observedOn" type="date" aria-label="Signal date" className={input}/><FormSelectMenu name="severity" defaultValue="info" options={[{value:"info",label:"Information"},{value:"watch",label:"Watch"},{value:"risk",label:"Risk"}]}/><textarea name="notes" aria-label="Signal notes" placeholder="Context and follow-up" className={input}/><button className={button} disabled={busy||!investments.length}>Record signal</button></form></section></div>
  {message&&<p role="status" className="text-[12px] text-cyan-800">{message}</p>}
  <section className="vq-card-static rounded-[14px] bg-white p-5"><h2 className="text-[15px] font-semibold text-ink">Signal history</h2>{!signals.length&&<p className="py-4 text-[12px] text-neutral-400">No external signals recorded.</p>}{signals.map(signal=><article key={signal.id} className="mt-3 border-t border-neutral-100 pt-3"><div className="flex flex-wrap justify-between gap-3"><a href={signal.source_url} rel="noopener noreferrer" target="_blank" className="text-[13px] font-semibold text-cyan-800">{signal.title}</a><span className="text-[11px] text-neutral-400">{signal.severity} · {signal.status} · {signal.observed_on}</span></div><p className="mt-1 text-[12px] text-neutral-500">{label(signal.investment_id)} · {signal.notes}</p><button disabled={busy} className="mt-2 text-[12px] font-semibold text-cyan-800" onClick={()=>start(async()=>{const result=await resolvePortfolioSignal(signal.id,signal.status!=="resolved");setMessage(result.message);router.refresh();})}>{signal.status==="resolved"?"Reopen":"Resolve"}</button></article>)}</section>
  </div>;
}
