"use client";
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import SelectMenu from "@/components/SelectMenu";
import Checkbox from "@/components/Checkbox";
import {setDealAccess,mergeCompanies} from "@/lib/workflows/governance-actions";
export default function WorkspaceGovernance({deals,acl,members,companies,canMerge,available}:{deals:{id:string;name:string;restricted:boolean}[];acl:{deal_id:string;member_email:string;access_role:string}[];members:{email:string;name:string}[];companies:{id:string;name:string}[];canMerge:boolean;available:boolean}){
  const [deal,setDeal]=useState(deals[0]?.id??""),[restricted,setRestricted]=useState(deals[0]?.restricted??false);
  const [roles,setRoles]=useState<Record<string,string>>(Object.fromEntries(acl.filter(a=>a.deal_id===deals[0]?.id).map(a=>[a.member_email,a.access_role])));
  const [keep,setKeep]=useState(""),[drop,setDrop]=useState(""),[message,setMessage]=useState("");const [busy,start]=useTransition();const router=useRouter();
  const button="rounded-full border border-neutral-200 px-4 py-2 text-[12px] font-semibold text-ink hover:border-cyan-400 disabled:opacity-40";
  return <div className="vq-card-grid grid gap-5 lg:grid-cols-2"><section className="vq-card rounded-[14px] bg-white p-5"><h2 className="text-[15px] font-semibold text-ink">Deal access</h2><p className="mt-1 text-[12px] text-neutral-500">Unrestricted deals use normal team access. Restricted deals require an explicit reader or editor; workspace admins retain access.</p>{!available?<p className="mt-3 text-[12px] text-neutral-500">Awaiting schema update.</p>:<><label className="mt-4 block text-[12px] text-neutral-600">Deal<SelectMenu value={deal} onChange={id=>{setDeal(id);setRestricted(deals.find(d=>d.id===id)?.restricted??false);setRoles(Object.fromEntries(acl.filter(a=>a.deal_id===id).map(a=>[a.member_email,a.access_role])));}} options={deals.map(d=>({value:d.id,label:d.name}))}/></label><label className="mt-4 flex items-center gap-2 text-[13px]"><Checkbox checked={restricted} onChange={e=>setRestricted(e.target.checked)}/>Restrict this deal</label>{restricted&&<div className="mt-4 max-h-80 overflow-y-auto">{members.map(member=><div key={member.email} className="grid grid-cols-2 items-center gap-3 py-2"><span className="text-[12px] font-medium text-ink">{member.name}</span><SelectMenu value={roles[member.email]??"none"} onChange={value=>setRoles(current=>({...current,[member.email]:value}))} options={[{value:"none",label:"No access"},{value:"viewer",label:"Reader"},{value:"editor",label:"Editor"}]}/></div>)}</div>}<button disabled={busy||!deal} className={`${button} mt-4`} onClick={()=>start(async()=>{const result=await setDealAccess(deal,restricted,Object.entries(roles).filter(([,role])=>role!=="none").map(([email,role])=>({email,role:role as "viewer"|"editor"})));setMessage(result.message);if(result.ok)router.refresh();})}>Save access</button></>}</section>
  <section className="vq-card rounded-[14px] bg-white p-5"><h2 className="text-[15px] font-semibold text-ink">Consolidate company identities</h2><p className="mt-1 text-[12px] text-neutral-500">Move company links to one identity while preserving separate investment rounds, documents, tasks, contacts and aliases. The merged record stays archived with its destination.</p><label className="mt-4 block text-[12px] text-neutral-600">Retain<SelectMenu value={keep} onChange={setKeep} options={companies.map(c=>({value:c.id,label:c.name}))} placeholder="Retained company"/></label><label className="mt-3 block text-[12px] text-neutral-600">Merge into retained company<SelectMenu value={drop} onChange={setDrop} options={companies.filter(c=>c.id!==keep).map(c=>({value:c.id,label:c.name}))} placeholder="Company to merge"/></label><p className="mt-3 text-[11px] text-neutral-400">Requires Admin, Documents and Portfolio permissions. Duplicate directory cards keep their content and become standalone cards.</p><button disabled={busy||!canMerge||!keep||!drop||keep===drop} className={`${button} mt-4`} onClick={()=>{if(!window.confirm(`Merge ${companies.find(c=>c.id===drop)?.name} into ${companies.find(c=>c.id===keep)?.name}? Separate rounds remain separate. This change cannot be undone from this page.`))return;start(async()=>{const result=await mergeCompanies(keep,drop);setMessage(result.message);if(result.ok){setDrop("");router.refresh();}});}}>Merge company identities</button></section>
  {message&&<p role="status" className="text-[13px] text-cyan-800 lg:col-span-2">{message}</p>}
  </div>;
}
