"""
Generate the private tracker backfill SQL.

Input:
  data/private/Company_Tracker_2025.csv

Output:
  supabase/private_seed/tracker_backfill.sql

The script verifies that the Nth deal insert in 0002_seed_tracker.sql matches
the Nth CSV row by company name before emitting SQL.
"""

from __future__ import annotations

import csv
import datetime as dt
import json
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "data" / "private" / "Company_Tracker_2025.csv"
SEED_0002 = ROOT / "supabase" / "migrations" / "0002_seed_tracker.sql"
OUT = ROOT / "supabase" / "private_seed" / "tracker_backfill.sql"
REPORT = ROOT / "docs" / "migration-report.md"

STATUS_TO_STAGE = {
    "Declined": "Declined",
    "Decline": "Declined",
    "Due Diligence": "Due Diligence",
    "Initial Discovery Session": "Initial Discovery",
    "Completed": "Completed",
    "Monitoring for future partnership and raise": "Monitoring / Future Raise",
    "In Active Conversations for Future Raise": "Monitoring / Future Raise",
}

OUTCOMES = {
    "Declined": "Declined",
    "Decline": "Declined",
    "Completed": "Completed",
}

RELATIONSHIP_STATES = {
    "Monitoring for future partnership and raise": "Monitoring / Future Raise",
    "In Active Conversations for Future Raise": "Active Future-Raise Conversation",
}

MONTHS = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12,
}


def esc(value: object | None) -> str:
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def parse_month(value: str | None) -> str | None:
    if not value:
        return None
    match = re.match(r"\s*([A-Za-z]+)\s*(\d{4})\s*$", value)
    if not match:
        raise ValueError(f"Could not parse month date: {value!r}")
    month = MONTHS[match.group(1)[:3].lower()]
    return dt.date(int(match.group(2)), month, 1).isoformat()


def normalize_status(value: str | None) -> str:
    text = (value or "").strip()
    if text == "Decline":
        return "Declined"
    return text


def stage_for_status(value: str | None) -> str:
    normalized = normalize_status(value)
    return STATUS_TO_STAGE.get(normalized, "Initial Discovery")


def parse_seed_order() -> list[dict[str, str]]:
    text = SEED_0002.read_text(encoding="utf-8")
    companies: dict[str, str] = {}
    company_re = re.compile(
        r"insert into companies \(id, name, industry_id\) values \('([^']+)', '((?:''|[^'])*)'",
        re.IGNORECASE,
    )
    for company_id, name in company_re.findall(text):
        companies[company_id] = name.replace("''", "'")

    deals: list[dict[str, str]] = []
    deal_re = re.compile(
        r"insert into deals .*? values \('([^']+)', '([^']+)', '((?:''|[^'])*)'",
        re.IGNORECASE,
    )
    for deal_id, company_id, deal_name in deal_re.findall(text):
        deals.append(
            {
                "deal_id": deal_id,
                "company_id": company_id,
                "company_name": companies[company_id],
                "deal_name": deal_name.replace("''", "'"),
            }
        )
    return deals


def month_columns(fieldnames: list[str]) -> list[str]:
    return [name for name in fieldnames if name.endswith(" Status") and name[:3] in {
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
    }]


def month_from_column(column: str) -> str:
    return parse_month(column.replace(" Status", ""))


def main() -> None:
    if not CSV_PATH.exists():
        raise SystemExit(f"Missing {CSV_PATH}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.parent.mkdir(parents=True, exist_ok=True)

    with CSV_PATH.open(newline="", encoding="utf-8-sig") as handle:
      reader = csv.DictReader(handle)
      rows = list(reader)
      months = month_columns(reader.fieldnames or [])

    seed_deals = parse_seed_order()
    if len(rows) != len(seed_deals):
        raise SystemExit(
            f"CSV row count {len(rows)} does not match 0002 deal count {len(seed_deals)}"
        )

    lines: list[str] = [
        "-- Private tracker backfill generated by scripts/generate_tracker_backfill.py",
        "begin;",
        "",
    ]
    history_rows = 0
    note_rows = 0
    parse_failures: list[str] = []
    duplicate_groups: dict[str, list[dict[str, str]]] = defaultdict(list)

    for index, row in enumerate(rows):
        seed = seed_deals[index]
        csv_name = row["name"].strip()
        if seed["company_name"] != csv_name:
            raise SystemExit(
                "Tracker row/deal mismatch at position "
                f"{index + 1}: CSV={csv_name!r}, 0002={seed['company_name']!r}"
            )

        row_ref = row["row"].strip()
        raw_status = row["status"].strip()
        current_stage = stage_for_status(raw_status)
        last_activity = parse_month(row.get("last_updated"))
        first_seen = parse_month(row.get("first_mentioned"))
        outcome = OUTCOMES.get(normalize_status(raw_status))
        relationship_state = RELATIONSHIP_STATES.get(raw_status)
        deal_id = seed["deal_id"]

        lines.append(f"-- tracker row {row_ref}: {csv_name}")
        lines.append(
            "update deals set "
            f"raw_source_status = {esc(raw_status)}, "
            "source_system = 'company_tracker_2025', "
            f"source_row_ref = {esc(row_ref)}, "
            "first_seen_precision = 'month', "
            f"first_seen_at = coalesce(first_seen_at, {esc(first_seen)}::date), "
            f"last_activity_at = {esc(last_activity)}::timestamptz, "
            f"outcome_id = {('(select id from deal_outcomes where name = ' + esc(outcome) + ')') if outcome else 'null'}, "
            f"relationship_state_id = {('(select id from relationship_states where name = ' + esc(relationship_state) + ')') if relationship_state else 'null'} "
            f"where id = {esc(deal_id)};"
        )

        previous = ""
        inserted_any_history = False
        for column in months:
            value = normalize_status(row.get(column))
            if not value:
                continue
            if value == previous:
                continue
            previous = value
            stage = stage_for_status(value)
            if not inserted_any_history and stage == current_stage:
                continue
            inserted_any_history = True
            changed_at = month_from_column(column)
            lines.append(
                "insert into deal_status_history "
                "(deal_id, stage_id, changed_at, changed_by, note, field_name, old_value_text, new_value_text, source) "
                "values ("
                f"{esc(deal_id)}, "
                f"(select id from pipeline_stages where name = {esc(stage)}), "
                f"{esc(changed_at)}::timestamptz, "
                "'migration:tracker', "
                f"{esc('Monthly tracker column ' + column)}, "
                "'stage', "
                "null, "
                f"{esc(value)}, "
                "'migration'"
                ");"
            )
            history_rows += 1

        for source_field, subject in (("note", "Tracker note"), ("lp_follow_up", "LP follow-up")):
            text = (row.get(source_field) or "").strip()
            if not text:
                continue
            lines.append(
                "insert into interactions "
                "(company_id, deal_id, type, occurred_at, subject, summary, created_by) "
                "values ("
                f"{esc(seed['company_id'])}, {esc(deal_id)}, 'note', "
                f"coalesce({esc(last_activity)}::timestamptz, now()), "
                f"{esc(subject)}, {esc(text)}, 'migration:tracker'"
                ");"
            )
            note_rows += 1

        duplicate_groups[csv_name.lower()].append(
            {
                "row": row_ref,
                "deal_id": deal_id,
                "status": raw_status,
                "industry": row.get("industry", ""),
                "priority": row.get("priority", ""),
                "first_mentioned": row.get("first_mentioned", ""),
                "last_updated": row.get("last_updated", ""),
            }
        )

        lines.append("")

    duplicate_count = 0
    for normalized_name, items in duplicate_groups.items():
        if len(items) < 2:
            continue
        duplicate_count += 1
        company_name = rows[seed_deals.index(next(d for d in seed_deals if d["deal_id"] == items[0]["deal_id"]))]["name"]
        payload = {"company_name": company_name, "deals": items}
        payload_sql = esc(json.dumps(payload, sort_keys=True))
        lines.append(
            "insert into review_items (review_type, status, payload) "
            f"select 'duplicate_tracker_row', 'open', {payload_sql}::jsonb "
            "where not exists ("
            "select 1 from review_items "
            "where review_type = 'duplicate_tracker_row' "
            f"and payload->>'company_name' = {esc(company_name)}"
            ");"
        )

    lines.extend(["", "commit;", ""])
    OUT.write_text("\n".join(lines), encoding="utf-8")

    report = f"""# Migration Report

Generated by `scripts/generate_tracker_backfill.py`.

## Tracker Backfill

- Source tracker rows: {len(rows)}
- Deals matched by 0002 order and company name: {len(seed_deals)}
- Monthly history rows generated: {history_rows}
- Note / LP follow-up interactions imported: {note_rows}
- Duplicate tracker groups queued for review: {duplicate_count}
- Parse failures: {len(parse_failures)}

## Portfolio Seed

Run `python scripts/generate_portfolio_seed.py` after placing the private audit CSVs in `data/private/`.
"""
    REPORT.write_text(report, encoding="utf-8")

    print(f"Wrote {OUT}")
    print(f"Wrote {REPORT}")
    print(f"{len(rows)} rows matched, {history_rows} history rows, {note_rows} notes")


if __name__ == "__main__":
    main()
