"""
Migrates Company_Tracker.xlsx (the original 139-row spreadsheet) into a
seed SQL file for the M1 schema: one `companies` row per unique company
name, one `deals` row per tracker row (so a company that appears twice
gets two deals — a re-entered pipeline opportunity, not silently merged),
and one `deal_status_history` row seeded from "Current Status" so the
Pipeline page has something real to show on day one.

Run: python3 scripts/generate_seed.py
Output: supabase/migrations/0002_seed_tracker.sql
"""
import datetime
import json
import re
import uuid

import openpyxl

SRC = "/mnt/user-data/uploads/Company_Tracker.xlsx"
OUT = "supabase/migrations/0002_seed_tracker.sql"

STAGE_MAP = {
    "Declined": "Declined",
    "Due Diligence": "Due Diligence",
    "Initial Discovery Session": "Initial Discovery",
    "Completed": "Completed",
    "Monitoring for future partnership and raise": "Monitoring / Future Raise",
    "In Active Conversations for Future Raise": "Monitoring / Future Raise",
}

MONTHS = {
    "jan": 1, "feb": 2, "mar": 3, "apr": 4, "may": 5, "jun": 6,
    "jul": 7, "aug": 8, "sep": 9, "oct": 10, "nov": 11, "dec": 12,
}


def parse_date(val):
    if val is None:
        return None
    if isinstance(val, (datetime.date, datetime.datetime)):
        return val.date().isoformat()
    if isinstance(val, str):
        m = re.match(r"([A-Za-z]{3,})\s+(\d{4})", val.strip())
        if m:
            mon = MONTHS.get(m.group(1)[:3].lower())
            if mon:
                return datetime.date(int(m.group(2)), mon, 1).isoformat()
    return None


def esc(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def main():
    wb = openpyxl.load_workbook(SRC, data_only=True)
    ws = wb["Company List 2025"]

    rows = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        name = row[0]
        if not name or not str(name).strip():
            continue
        rows.append({
            "name": str(name).strip(),
            "status": (row[1] or "").strip(),
            "industry": (row[2] or "").strip() or None,
            "first_mentioned": parse_date(row[3]),
            "last_updated": parse_date(row[4]),
            "priority": (row[21] or "Medium").strip() or "Medium",
        })

    industries = sorted({r["industry"] for r in rows if r["industry"]})
    company_names = sorted({r["name"] for r in rows})

    lines = []
    lines.append("-- Seed data migrated from Company_Tracker.xlsx")
    lines.append(f"-- {len(rows)} tracker rows -> {len(company_names)} unique companies, "
                  f"{len(rows)} deals. Generated by scripts/generate_seed.py.\n")

    lines.append("-- Industries")
    industry_ids = {}
    for ind in industries:
        iid = str(uuid.uuid4())
        industry_ids[ind] = iid
        lines.append(
            f"insert into industries (id, name) values ({esc(iid)}, {esc(ind)}) "
            f"on conflict (name) do nothing;"
        )

    lines.append("\n-- Companies")
    company_ids = {}
    # Use the most recent row's industry for the company record
    first_industry_seen = {}
    for r in rows:
        if r["name"] not in first_industry_seen and r["industry"]:
            first_industry_seen[r["name"]] = r["industry"]
    for name in company_names:
        cid = str(uuid.uuid4())
        company_ids[name] = cid
        ind = first_industry_seen.get(name)
        ind_sql = f"(select id from industries where name = {esc(ind)})" if ind else "NULL"
        lines.append(
            f"insert into companies (id, name, industry_id) values "
            f"({esc(cid)}, {esc(name)}, {ind_sql});"
        )

    lines.append("\n-- Deals + seeded status history")
    unmapped_statuses = set()
    for r in rows:
        did = str(uuid.uuid4())
        stage_name = STAGE_MAP.get(r["status"])
        if not stage_name:
            unmapped_statuses.add(r["status"])
            stage_name = "Initial Discovery"
        cid = company_ids[r["name"]]
        deal_name = f"{r['name']} — tracker import"
        first_seen = f"'{r['first_mentioned']}'" if r["first_mentioned"] else "NULL"
        priority = r["priority"] if r["priority"] in ("High", "Medium", "Low") else "Medium"

        lines.append(
            f"insert into deals (id, company_id, name, stage_id, priority_id, owner, source, first_seen_at) "
            f"values ({esc(did)}, {esc(cid)}, {esc(deal_name)}, "
            f"(select id from pipeline_stages where name = {esc(stage_name)}), "
            f"(select id from priorities where name = {esc(priority)}), "
            f"'Scott', 'Tracker migration', {first_seen});"
        )
        lines.append(
            f"insert into deal_status_history (deal_id, stage_id, changed_by, note) values "
            f"({esc(did)}, (select id from pipeline_stages where name = {esc(stage_name)}), "
            f"'migration', 'Migrated from Company_Tracker.xlsx (original status: {r['status'] or 'unknown'})');"
        )

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {OUT}")
    print(f"{len(rows)} rows, {len(company_names)} unique companies, {len(industries)} industries")
    if unmapped_statuses:
        print("Unmapped statuses (defaulted to Initial Discovery):", unmapped_statuses)


if __name__ == "__main__":
    main()
